services:
  app:
    image: python:alpine
    working_dir: /app
    volumes: 
      - type: bind
        source: ./app/
        target: /app
    ports:
      - 127.0.0.1:3000:3000
    environment:
      HOST: postgres
      PASSWORD: devtest
      USER: postgres
    #tty: true
    #stdin_open: true
    #command: sh -c "pip install -r requirements.txt && /bin/ash"
    command: sh -c "pip install -r requirements.txt && python vendOmatic.py"
  postgres:
    image: postgres:alpine
    working_dir: /database
    volumes:
      - ./database:/database
    environment:
      POSTGRES_PASSWORD: devtest
      PGDATA: /database/
